### ISSUE TITLE
Bad private key

### ISSUE THREAD

**Issue by Ryusmay** [zilpay/zilpay-mobile#10]
Hello.  I have a little problem.  I imported my wallet wrong by typing the secred phrase instead of private key and forgot to delete this account.  in error, I sent some of my zils and threads to this wallet.  now I can't send them anywhere else because an error pops up over the private key.  is it possible to get my coins back?

**Comment by Ryusmay** [comment]
if it helps, I drop the address zil1gvjqs70adx20w2sh36ekv48xn3v0pwemu3upyz 
I checked on the computer and it is impossible to make the mistake I made on the phone assuming the wrong private key

**Comment by Ryusmay** [comment]
it is a very serious error that it was possible to generate a wallet with an incorrect private key and the night of t now cannot be done to recover funds from it

**Comment by Ryusmay** [comment]
when importing the wallet, you can enter any words and characters that are not a valid private key.  instead of the message about an incorrect private key, the application will generate a new wallet to which you can transfer the coins, but you can not take them out because there will be a message that the private key is wrong.  this leads to a very quick loss of coins even if a small mistake is made when entering the private key.  Hopefully it will be fixed quickly and I will get some kind of refund for my lost coins or a chance to get them back

**Comment by hicaru** [comment]
Thanks for your issue, i will try implement your problem

**Comment by hicaru** [comment]
Helo, it has only one solution, you need convert your secret phrase to bytes after it you can sign tx

**Comment by Ryusmay** [comment]
how to do it?

**Comment by hicaru** [comment]
you can use any programming language for it. The best way use python

**Comment by hicaru** [comment]
added validator of privateKey for beginner users in https://github.com/zilpay/zilpay-mobile/releases/tag/0.0.9

**Comment by Ryusmay** [comment]
it doesn't work that way or I can't make good use of it.  this means that I lost some of my funds due to the lack of security in the application.  I am dissatisfied with this and do not know how to solve it now, it would be good to receive compensation for lost funds.  good that the bug has been fixed and no one will lose their crypto anymore.
