### ISSUE TITLE
Unable To Verify Transaction

### ISSUE THREAD

**Issue by defrizacrypto** [zilpay/zilpay-mobile#11]
It looks like my wallet is broken, when I wanted to unlock a token it turned out I couldn't and the words 'Unable To Verify Transaction' came out, zilpay telegram admin says 'this is an error of bad signature', what should I do, my wallet contains PORT Tokens and some ZIL, help me
![Screenshot_2021-03-25-00-53-51-30_923935dfe10564382272ade746ce6c0e](https://user-images.githubusercontent.com/80095268/112360824-511add00-8d05-11eb-8921-c9751e6ad265.jpg)

**Comment by hicaru** [comment]
This error from blockchain, when your signature is incorrect, if you just import wallet, try upgrade your ZIlPay version to last, and try import your account again.

**Comment by defrizacrypto** [comment]
I have updated Zilpay to the latest version, and also re-imported my wallet
but it still doesn't matter.

Pada tanggal Sab, 27 Mar 2021 4.46 PM, Rinat ***@***.***>
menulis:

**Comment by hicaru** [comment]
if you have imported seed phrase instead privatekey, you can see it. For sign tx you need split your secret phrase to bytes after convert to HEX. after it you can sign tx manually

**Comment by hicaru** [comment]
added validator of privateKey for beginner users in https://github.com/zilpay/zilpay-mobile/releases/tag/0.0.9

**Comment by defrizacrypto** [comment]
Okay, I'll update, if something goes wrong I'll report it again. Thank you,
Have a good day

Pada tanggal Min, 28 Mar 2021 5.48 PM, Rinat ***@***.***>
menulis:
