### ISSUE TITLE
Cannot send to my Wallet.

### ISSUE THREAD

**Issue by YURI1409** [zilpay/zilpay-mobile#12]
Hello,
I cannot send Zilliga to my Atomic or Trust Wallet.
I  van receiver and swap with zilswap.!
I is Evert time rejected.

**Comment by hicaru** [comment]
for understand need full details, like OS, Version of ZIlPay, device, device model, user story, errors message

**Comment by hicaru** [comment]
fixed calculate max balance in 0.0.8 version
