### ISSUE TITLE
Cannot connect Ledger 

### ISSUE THREAD

**Issue by uribem001** [zilpay/zilpay-mobile#13]
I am unable to connect my Ledger through the ZilPay iOS app.

**Comment by hicaru** [comment]
Hello, sorry but there have an issue, when i will get the ledger nano x, i can fix it

**Comment by junwei2012** [comment]
> Hello, sorry but there have an issue, when i will get the ledger nano x, i can fix it

Hi will this issue be resolved any time soon ? Wish to connect my ledger too

**Comment by hicaru** [comment]
added this release [0.1.6](https://github.com/zilpay/zilpay-mobile/tree/0.1.6)
