### ISSUE TITLE
Can't add token. Is not ZRC message

### ISSUE THREAD

**Issue by ghost** [zilpay/zilpay-mobile#14]
Hello, I'm a developer of ZPN token. Our users struggling with issues being unable to add out a token to their wallets. They keep getting an error "Is not ZRC message".

Our contract address is: zil10w6ukup76ljmvgn4c25e5kpkjehe6a7vqa5r3y

On the Chrome extension version, everything works like a charm

**Comment by hicaru** [comment]
Thanks for your an issue, i will check it

**Comment by hicaru** [comment]
Hello again, i checked your contract. In your contract field `name` is empty
