### ISSUE TITLE
Bad private key

### ISSUE THREAD

**Issue by Ryusmay** [zilpay/zilpay-mobile#15]
it doesn't work that way or I can't make good use of it. this means that I lost some of my funds due to the lack of security in the application. I am dissatisfied with this and do not know how to solve it now, it would be good to receive compensation for lost funds. good that the bug has been fixed and no one will lose their crypto anymore. is it possible to generate a key using the secret phrase and wallet address?

**Comment by hicaru** [comment]
Hello, all the data store on your device, Check the Privacy Policy! If you made mistake this is only your mistake

**Comment by Ryusmay** [comment]
Yes, this is my bug that should be stopped by applications, as is the case with all other wallets. The application error is also important and thanks to me you could fix it so that others do not lose their money. I still think it's your fault because the app didn't stop me making a mistake, and it should have implemented such protections from the very beginning
