### ISSUE TITLE
I have done my 13  E-commerce scans.but I don't have any port token in my zilpay wallet ..why...it's scam..

### ISSUE THREAD

**Issue by harishchauhan911** [zilpay/zilpay-mobile#17]
I have done my 13  E-commerce scans.but I don't have any port token in my zilpay wallet ..why...it's scam..

**Comment by vishu870** [comment]
Where did my token ar

**Comment by hicaru** [comment]
ZILPAY DOESN'T NOTHING TO DO WITH THE FUCKING PORT
