### ISSUE TITLE
Restore wallet

### ISSUE THREAD

**Issue by Ryusmay** [zilpay/zilpay-mobile#23]
can add the ability to renew the wallet with a QR code but generate a keystore file

**Comment by hicaru** [comment]
Hello this already have got, you can connect it from ZIlPay extension

**Comment by Ryusmay** [comment]
I mean adding such an option directly to the application on the phone

**Comment by hicaru** [comment]
ok, thanks for this an issue, i will implement it

**Comment by Cbbipul96** [comment]
How to restore wallet

**Comment by hicaru** [comment]
click to new wallet -> connect -> scan QRcode

**Comment by Cbbipul96** [comment]
Lol😋

Old Trick 🤣
