### ISSUE TITLE
secret prase bug

### ISSUE THREAD

**Issue by kiwina** [zilpay/zilpay-mobile#3]
Hi, was just trying it and when creating the wallet there was a duplicate word, witch when confirming the phrase does not come up.

**Comment by hicaru** [comment]
could you show your device info and screenshots

**Comment by kiwina** [comment]
have a look https://prnt.sc/wfe695

**Comment by Optelic** [comment]
Iphone 12. Trying to restore from secret phrase. App will not allow me to click continue once the phrase has been entered.

**Comment by hicaru** [comment]
@kiwina thanks for details i will fix it in new version.

**Comment by hicaru** [comment]
@Optelic all the words should be lowercase with spaces between words
