### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by Charlesgohxy** [zilpay/zilpay-mobile#31]
In the browser, when clicking on any of the categories, it displays "Have no applictations yet". Spelling error on applications.

**Comment by hicaru** [comment]
Yes, your are right i will fix it in new version of ZIlPay.

**Comment by Charlesgohxy** [comment]
Thanks!

Am looking forward to future updates!

**Comment by hicaru** [comment]
fixed in 0.1.0 version
