### ISSUE TITLE
"fail credentials" error when using account with imported private key

### ISSUE THREAD

**Issue by zilpayblocked** [zilpay/zilpay-mobile#39]
I recently imported my wallet in zilpay, by private key.

when I connect to zilswap and claim zwap, it asks my password, then I click "send", then zilpay tells me in red "fail credentials". I removed the wallet and created it again, to make sure I have the right password. I still have the same error.
Same when I simply try to send zilliqa.

my phone is a moto g8, Android 10. Zilpay 0.0.9 android.
I get the same issue on a xiaomi redmi 6.
enabling storage permission didn't resolve the issue

**Comment by zilpayblocked** [comment]
![zilpaybug](https://user-images.githubusercontent.com/82518961/114767746-4ed9fa80-9d68-11eb-9185-4ac06b5467b8.png)

**Comment by hicaru** [comment]
Hello, hanks for your issue it is already fixed and will be in new version.

**Comment by hicaru** [comment]
fixed in 0.1.0 version

**Comment by Roshan7888** [comment]
Same problem fail credentials problem

**Comment by Roshan7888** [comment]
How to solution
