### ISSUE TITLE
Unable to key in contract address for other tokens in iOS

### ISSUE THREAD

**Issue by angerfear** [zilpay/zilpay-mobile#4]
Reporting a visual bug of not able to paste or see what I key in when adding contract address. 

The keyboard will cover up the area. 
![034B6315-F95D-46ED-9D53-BC3EDE35C914](https://user-images.githubusercontent.com/78054154/105917727-b9cf3b80-606d-11eb-9708-49dfc8bd8aa1.jpeg)
![4A927E5E-0F51-4EDA-B340-8CD94D05E535](https://user-images.githubusercontent.com/78054154/105917733-bc319580-606d-11eb-99fd-f394b1964ad4.jpeg)

**Comment by hicaru** [comment]
thanks for this issue it will be fix
