### ISSUE TITLE
Gasprice 1000000000 lower than minimum allowable 2000000000

### ISSUE THREAD

**Issue by zilpayblocked** [zilpay/zilpay-mobile#41]
I can't send zil or tokens, even if I pick the highest fee available.
I always got the error "Gasprice 1000000000 lower than minimum allowable " after clicking send.
zilpay 0.1.0

**Comment by hicaru** [comment]
Hello, thanks for this issue, ZIlliqa upgraded blockchain config and changed min gasLimit from 1 to 50. Now it is changed to on ZIlPay but google still review it.

**Comment by bama88** [comment]
Hey! I’m dealing with the same problem. 
How did you resolve it? Were you able to send your ZIL to an other wallet?

I will appreciate your help!
