### ISSUE TITLE
Private key issues

### ISSUE THREAD

**Issue by muhzaid** [zilpay/zilpay-mobile#42]
hello, i need your help why my wallet account private key in the form of text? i create a new one and then it is a number
https://prnt.sc/11sn15x here text private key

**Comment by hicaru** [comment]
Hello, did you import your secret phrase where written `input privateKey`?

**Comment by muhzaid** [comment]
im using multi account in my zillapp, so if im need login to my zilpay extensions need private key. but in my case i dont know why my private key is text

**Comment by muhzaid** [comment]
if im written that my text private key then its not work its say error

**Comment by muhzaid** [comment]
http://prntscr.com/11t39un

**Comment by hicaru** [comment]
why you are inputing secret phrase, where written privateKey?

**Comment by muhzaid** [comment]
did u see that my private key is like secret phrase so i cant login with that dude

**Comment by hicaru** [comment]
you need click to new wallet on lock page -> restore -> input secret phrase

**Comment by Ryusmay** [comment]
I have exactly the same problem.  my private key is my secret phrase.  I cannot fix it in any way, and I cannot recover my zil

**Comment by hicaru** [comment]
this is possible if you  input secret phrase where written `input privateKey` privateKey is very different of secret phrase.
