### ISSUE TITLE
Money has disappeared from Zilpay Wallet

### ISSUE THREAD

**Issue by tawhidx2** [zilpay/zilpay-mobile#44]
![Screenshot_20210512-135053](https://user-images.githubusercontent.com/83280230/117938649-160e5080-b329-11eb-81fa-7d94a1e8dcdb.png)

Plz help me sir 
My port token is missing

Zilpay address: zil1uax03tjscd73zv2menukm0gmswxzhpy4ueqxrx

**Comment by hicaru** [comment]
ZIlliqa upgrading network
