### ISSUE TITLE
Confirmation for sending tokens displays contract address

### ISSUE THREAD

**Issue by dchooyc** [zilpay/zilpay-mobile#45]
Should the confirmation page and history display just the contract address as the sent to address?

**Comment by dchooyc** [comment]
- Just confirmed that the token was actually sent to CORRECT address. 

But the app displays a previous address after continue is tapped on the Confirmation page. After sending a previous address is still displayed as sent to but the token is really sent to the CORRECT address.

Possibly a cache issue where the text in the confirmation page is stuck with a previous value and thus the history also displays the confirmation page's value. 

But the transaction is successful to the correct, which is a different, address.

**Comment by hicaru** [comment]
Hello it just actually recipient, we haven't any tool for detect token standard yet

**Comment by dchooyc** [comment]
@hicaru maybe when any token is sent, recipient is shown instead of contract address and especially when the recipient is a saved contact, it show show as the name the contact is saved as

**Comment by hicaru** [comment]
Nice idea i will do that, thanks for your issue.

**Comment by hicaru** [comment]
fixed in https://github.com/zilpay/zilpay-mobile/releases/tag/0.2.0
