### ISSUE TITLE
Cant import my ledger account

### ISSUE THREAD

**Issue by HarryMonk09** [zilpay/zilpay-mobile#5]
Hi

I have 2 wallets on my desktop. After installing the android app, I managed to import my non ledger wallet using the restore function by using the secret phase. 

Only one of my wallets was imported so went to try and import my ledger wallet. I click on ledger but the import button just doesn't do anything.

My Bluetooth is on and even tried with it plugged in via cable to my phone. Am i doing something wrong??

Thanks

**Comment by hicaru** [comment]
![2021-02-08 12 06 08](https://user-images.githubusercontent.com/21293723/107186425-13d4e700-6a06-11eb-85d6-03914d9a2c71.jpg)

thanks for this issue

**Comment by AHaliq** [comment]
Hi, I'm having the same issue. I'm able to add my ledger account on my mac via zilpay chrome extension.

Upon checking it on zilpay mobile app, the account is not shown. I tried adding the ledger but pressing the import account button does nothing.

I'm able to connect my ledger on the ledger live app via bluetooth.

**Comment by hicaru** [comment]
Hello this was fixed in [0.1.6](https://github.com/zilpay/zilpay-mobile/tree/0.1.6) version
