### ISSUE TITLE
Dependency error when running `npm i`

### ISSUE THREAD

**Issue by re2005** [zilpay/zilpay-mobile#54]
Trying to run it locally and got this dependency errors when installing.

![Screenshot 2021-09-27 at 07 36 34](https://user-images.githubusercontent.com/2920357/134850618-e33e67f1-e52f-4a3e-8dd4-04ce58259526.png)

Any help is appreciated.

**Comment by hicaru** [comment]
Hello try use yarn

**Comment by hicaru** [comment]
What the node version are you using?
