### ISSUE TITLE
Listening to: observableNetwork keeps on triggering

### ISSUE THREAD

**Issue by re2005** [zilpay/zilpay-mobile#57]
Hi first I want to say: great job with the APP!

I'm using:

window.zilPay.wallet.observableNetwork().subscribe(() => {}

And this keeps on being called, when running my app inside the mobile.

Normally I reload the APP when network changes, but inside the mobile, keeps on reloading the page forever.

Is this an expected behaviour or I'm doing something wrong here?
On desktop works just fine.

**Comment by hicaru** [comment]
hello thanks for your issue i will check and fix in new releases.
