### ISSUE TITLE
Zilpay l cant exhane

### ISSUE THREAD

**Issue by aldem1905** [zilpay/zilpay-mobile#60]
I have not been able to trade in my wallet for 3 days. I am a new member to zilpay and I think I accidentally registered to a place like stake, can you please solve the problem
![Screenshot_20211108-184724_Chrome](https://user-images.githubusercontent.com/93885591/140792808-3646fc04-c595-4812-b0c3-61a4096a03a2.jpg)

**Comment by hicaru** [comment]
Hello, ZIlPay have no any exchanges, if you have an issue on Dapps you should ask them support.
