### ISSUE TITLE
I'm transferred Zil cryto binance to zilpay

### ISSUE THREAD

**Issue by velstore01** [zilpay/zilpay-mobile#62]
![Screenshot_2021-11-15-20-59-50-45_ee1cec40dcf6eb3919ecbfc5d87e6719](https://user-images.githubusercontent.com/75827930/141809109-c5ed172a-8932-4f39-b77b-4b0afc4f0465.jpg)

Not received 217 zil crypto 22usd Value

**Comment by hicaru** [comment]
you received, just check your netwrok connection or node which are you using!
