### ISSUE TITLE
I lost my coins

### ISSUE THREAD

**Issue by Love7456** [zilpay/zilpay-mobile#68]
I sent my zill coins from Binance to my wallet, but my coins didn't arrive
![Screenshot_20220201_121106_com binance dev](https://user-images.githubusercontent.com/98809542/151946223-f184cccc-1542-472e-97a9-350ab740ecec.jpg)

**Comment by Love7456** [comment]
Hi sir Why don't answer?

**Comment by hicaru** [comment]
hello, you was using incorrect address format! Use only bech32

**Comment by Love7456** [comment]
There is no other address


في الجمعة، ٤ فبراير، ٢٠٢٢ ٩:٥٢ م Rinat ***@***.***> كتب:
