### ISSUE TITLE
Wallet balance

### ISSUE THREAD

**Issue by 3dgar123** [zilpay/zilpay-mobile#73]
I send 299 a my zil wallet like 1 hour ago. It appears with a hash number but is not reflected in my wallet balance.

**Comment by 3dgar123** [comment]
I need answer of zilpay? Where is my new balance with my last buy of 299?

**Comment by hicaru** [comment]
Hello, try change node API or check your internet connection

**Comment by 3dgar123** [comment]
Who I change the node API?

**Comment by hicaru** [comment]
in the Settings > Netwrok > click to current node and click to update, after update you can chose any node
