### ISSUE TITLE
XCAD not showing in wallet after swap

### ISSUE THREAD

**Issue by Scrobwofl** [zilpay/zilpay-mobile#74]
Hi, I converted some zusd to zil, and then from zil to xcad. The zil showed up after I used the xcad dex to convert but the xcad conversion isn't. It's 100% there on the blockviewer and the transaction was a success, but its not showing in the app.

https://viewblock.io/zilliqa/tx/7caab7ece5b23c90c371fc4b6738cc52ceeef1364086e0032048aa535a719238?network=mainnet

**Comment by hicaru** [comment]
Hello, yes, XCAD has 2 different tokens, try disable and enable xcad token.
