### ISSUE TITLE
0 in wallet

### ISSUE THREAD

**Issue by plex99** [zilpay/zilpay-mobile#76]
Hello,
Is this some kind of bug?
Yesterday checked my wallet, everything was ok. Today checked and wallet shows that I have 0 zil and 0 every token that I owned. No transactions where made so I assume it wasnt a hack.

please help

**Comment by 3Misfits** [comment]
Same issue here.  Noticed last night when it occurred had an error showing: Update
JSON Parse error:
Unrecognized token
"‹'

now there’s nothing showing in the account, even though transaction history is correct.  It’s not connecting to zil staking site either

**Comment by raju0092** [comment]
Same issue here. Noticed last night when it occurred had an error showing: Update
JSON Parse error:
Unrecognized token
"‹'

now there’s nothing showing in the account, even though transaction history is correct. It’s not connecting to zil staking site either

**Comment by hicaru** [comment]
Hello it was ZIlliqa network issue.
