### ISSUE TITLE
Can’t send 

### ISSUE THREAD

**Issue by jwteknix** [zilpay/zilpay-mobile#9]
Unable to send from wallet no problem receiving. Unable to verify transaction  is the displayed error. Thanks

**Comment by hicaru** [comment]
Hello thanks for your issue, i need more details. Like error text, device model, OS version.

**Comment by jwteknix** [comment]
Wow thanks for the reply I’ve been having issues for months, and trying to reach out to some one. I’m having a couple issues not sure if they’re all related. My wallet address zil18aqxhmkhp5k4yn4pvlk5dwcjn99qf5c3dvhv2a I have access on the mobile app but am unable to link it to the chrome browser for some reason it keeps telling me the wallet was already added but I have no access. I have both secret password and 12 word phrase. When trying to send to a different wallet this is the error I receive I’ve read it’s possible to get this message due to note enough zil to cover fees sit that’s not the case I’ve been able to deposit to this address no problem. I have an iPhone 11 Pro, and am probly on the first version of the app. Thank you very much, any help is appreciated.
James

**Comment by hicaru** [comment]
Hello thanks for details, for now it was fixed, but i cannot publish new version, because Apple removed ZIlPay from Appstore, when i will sign contract with apple, i will publish new version with all fixes. Thanks!

**Comment by jwteknix** [comment]
Thank you for the response, is there any eta on that? It’s good to know my stuff isn’t lost forever.

**Comment by hicaru** [comment]
you are welcome

**Comment by jwteknix** [comment]
Any estimated time on the release, so I can use my funds on zilswap.
 Thanks James
